# NUMPY BASICS

## WHAT IS NUMPY ?

### NumPy (Numerical Python) is a Python library used for numerical computations. It provides:

### A powerful array object for handling large datasets.
### Functions for mathematical operations, linear algebra, statistics, and more.


## 2.KEY CONCEPTS IN NUMPY 

## 2.1 NUMPY ARRAY 

## Creating arrays

In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
print("Array a:", a)  # [1 2 3]
print("Array b:", b)  # [[1 2 3] [4 5 6]]

Array a: [1 2 3]
Array b: [[1 2 3]
 [4 5 6]]


# Shape and size

In [7]:

print("Shape of b:", b.shape)  # (2, 3)
print("Size of b:", b.size)    # 6

Shape of b: (2, 3)
Size of b: 6


### shape determines the dimensions while the size determines the elements

# 2. ARRAY OPERATIONS

In [13]:

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [15]:
x+y

array([5, 7, 9])

## Element-wise operations

In [18]:
print("x + y:", x + y)  # [5 7 9]
print("x * y:", x * y)  # [4 10 18]

x + y: [5 7 9]
x * y: [ 4 10 18]


# Broadcasting

In [21]:
z = np.array([1, 2, 3])
print("z + 5:", z + 5)  # [6 7 8]

z + 5: [6 7 8]


### this is adding value to all the elements in an array

### another example

In [25]:
print("z+10",z+10)

z+10 [11 12 13]


# Aggregation

In [28]:
print("Sum of x:", np.sum(x))   # 6
print("Mean of y:", np.mean(y))  # 5.0

Sum of x: 6
Mean of y: 5.0


### The above is how to find mean and sum of a given data set given

# 3. INDEXING AND SLICING

In [32]:
arr = np.array([10, 20, 30, 40, 50])

### Basic Indexing

In [36]:

print("Element at index 2:", arr[2])  # 30

Element at index 2: 30


In [38]:
print("Element at index 3:", arr[3])  # 40

Element at index 3: 40


## Slicing

In [41]:
print("Slice from index 1 to 4:", arr[1:4])  # [20 30 40]


Slice from index 1 to 4: [20 30 40]


### this is how to access and slice index from a given data set

### Boolean Indexing

In [45]:
print("Elements greater than 25:", arr[arr > 25])  # [30 40 50]


Elements greater than 25: [30 40 50]


### The above is how to determine the largest or the smallest value in an array

#### Fancy Indexing

In [50]:
indices = [0, 2, 4]
print("Elements at indices 0, 2, 4:", arr[indices])  # [10 30 50]

Elements at indices 0, 2, 4: [10 30 50]


### the above is how to access many indexes at the same time

## 4. SHAPE MANIPULATION

In [54]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])


## reshaping

In [57]:
reshaped = matrix.reshape(3, 2)
print("Reshaped matrix:\n", reshaped)

Reshaped matrix:
 [[1 2]
 [3 4]
 [5 6]]


### reshaping is modifying the matrix to any choice oone choose so long as the number of elements match

## Flattening

#### this is how to flatten a matrix in datascience


In [63]:
flat = matrix.flatten()
print("Flattened matrix:", flat)  # [1 2 3 4 5 6]


Flattened matrix: [1 2 3 4 5 6]


##  Transposing

In [67]:
transposed = matrix.T
print("Transposed matrix:\n", transposed)

Transposed matrix:
 [[1 4]
 [2 5]
 [3 6]]


#### the above is how to transpose a matrix in software

## 5. MATHEMATICAL FUNCTIONS

numbers = np.array([1, 2, 3, 4, 5])

### Basic Math

In [74]:
print("Add 5 to each element:", np.add(numbers, 5))  # [6 7 8 9 10]
print("Multiply each element by 2:", np.multiply(numbers, 2))  # [2 4 6 8 10]


Add 5 to each element: [ 6  7  8  9 10]
Multiply each element by 2: [ 2  4  6  8 10]


### Statistical Functions

In [77]:
print("Mean:", np.mean(numbers))  # 3.0
print("Standard Deviation:", np.std(numbers))  # 1.4142
print("Variance:", np.var(numbers))  # 2.0

Mean: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


### Linear Algebra

In [80]:
matrix = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### The above is how to determine the inverse of a matrix using numpy and dot product

In [84]:
matrix = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

dot_product = np.dot([1, 2], [3, 4])
print("Dot product:", dot_product)  # 1

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Dot product: 11


# 6. RANDOM MODULE

## Random Number Generation

In [91]:
random_array = np.random.rand(3)
print("Random array:", random_array)

random_integers = np.random.randint(1, 10, size=3)
print("Random integers:", random_integers)


Random array: [0.52553484 0.68731192 0.09687173]
Random integers: [3 1 7]


### The above is how to get random numbers and how to generate integers of any size one may want

## Reproducibility

In [97]:
np.random.seed(42)
print("Seeded random array:", np.random.rand(3))

Seeded random array: [0.37454012 0.95071431 0.73199394]


In [101]:
np.random.seed(42)
print("Seeded random array:", np.random.rand(3))

Seeded random array: [0.37454012 0.95071431 0.73199394]


### This what makes the code reproducible without making the code more random

# 7. FILE I/O

## Saving and Loading Arrays

In [106]:
arr_to_save = np.array([1, 2, 3, 4, 5])
np.save('array_file.npy', arr_to_save)

loaded_arr = np.load('array_file.npy')
print("Loaded array from .npy:", loaded_arr)

Loaded array from .npy: [1 2 3 4 5]


In [108]:
loaded_arr

array([1, 2, 3, 4, 5])

## Working with Text Files

In [111]:
np.savetxt('array_file.txt', arr_to_save)
loaded_txt = np.loadtxt('array_file.txt')
print("Loaded array from .txt:", loaded_txt)

Loaded array from .txt: [1. 2. 3. 4. 5.]


# 8. PERFORMANCE (VECTORIZATION)

In [114]:
import time

### Using loops (slow)

In [117]:
start = time.time()
list_comp = [x**2 for x in range(1000000)]
end = time.time()
print(f"List comprehension time: {end - start} seconds")

List comprehension time: 0.25531578063964844 seconds


#### The above is the time taken to handle the list compressions but it takes much time hence not advisable

### Using NumPy (fast)

### This uses little time compared to list compressions or using loops

In [120]:
start = time.time()
numpy_comp = np.arange(1000000)**2
end = time.time()
print(f"NumPy vectorized time: {end - start} seconds")

NumPy vectorized time: 0.0049855709075927734 seconds
